In [2]:
import numpy as np

In [25]:
w_array_text = """weight 0: [ 146.888  257.333  120.706 -273.091  597.232   77.819 -430.544   66.271
  214.027 -211.351  136.076]
weight 1: [ 151.84   261.561  152.338 -272.295  591.847   78.536 -436.542   64.379
  235.861 -211.145  110.738]
weight 2: [ 211.583  328.489   53.33  -220.76   702.032  129.999 -320.664  -65.465
  180.864 -208.053   51.527]
weight 3: [ 164.4    285.676   63.307 -210.435  676.681  139.513 -344.925 -107.006
  178.651 -210.097   49.383]
weight 4: [  65.809  173.363  110.006 -181.788  600.639  169.768 -428.017 -142.651
  211.812 -215.466   95.723]
weight 5: [  32.462  124.797   91.19  -205.156  548.725  145.624 -496.127  -64.634
  135.804 -217.559   85.628]
weight 6: [  86.098  210.342   51.785 -250.142  468.439   85.601 -577.18   -71.54
   65.41  -213.74    89.187]
weight 7: [ 2146.684  1538.89   -287.28   6000.346  2658.638  5182.37  -5649.848
  3709.604  -649.873  -592.218   315.839]
weight 8: [  215.923  2032.612  -307.14   4858.851  3811.383  4175.584 -5591.423
  3293.974  -818.303  -414.247   -80.826]
weight 9: [ 3988.966 -1350.19    -35.625  8746.506 -5069.721 -6418.718  3286.506
   899.546   142.487 -4889.011   599.992]
weight 10: [-1101.06   2078.328   -38.97   -350.694  -749.869  -919.739   396.954
  -618.764     9.482  -175.263    94.298]
weight 11: [-1586.385  1157.597    91.108  -300.593  1057.662    80.127  -528.462
  -214.416   107.073  -301.226   -96.677]
weight 12: [  4608.547 -10000.      1516.024 -10000.      4655.107   2352.406
  -5134.776  -9319.877     76.394  10000.       -31.511]
weight 13: [  4245.458 -10000.      1751.842  -9966.641   8579.265  10000.
 -10000.      -761.065    283.553  10000.        43.47 ]
weight 14: [  4942.171 -10000.      1356.195  -2991.439   3451.617   2831.782
  -4260.91    -580.741    -52.015  10000.        18.224]
weight 15: [  5715.148 -10000.       714.685  -1389.082  -2116.034   1596.408
   2401.327   -467.469   -191.809   9615.925     23.493]
weight 16: [ -295.501 -1836.025  2548.581  1251.479 -3642.348   968.146  3826.496
  1978.079  -756.226 -3901.254   -16.551]
weight 17: [-7168.865  5922.395  4533.053  1673.605 -7314.708   153.401  7014.891
  1334.677 -1960.264  -309.534   -32.893]
weight 18: [ -141.302 -2320.344  2733.446  1289.478 -2105.02   1159.347  1938.395
  2020.254  -769.129 -1219.562   -46.146]
weight 19: [-3609.108  1796.174  3678.586  1251.668 -4763.479  -752.702  4819.984
   557.456 -1161.388 -1652.734   -58.86 ]
weight 20: [-2880.179  1125.017  3404.938   803.732 -3650.063 -1168.023  3507.463
    61.23  -1085.577 -2951.012   -56.384]
weight 21: [  605.646 -2037.946  1727.227   -83.636   376.131   895.587  -672.694
   373.972  -274.614   -57.755   -39.912]
weight 22: [ 3.654e+03 -4.780e+03 -8.253e+01 -1.000e+04  2.452e+03  3.783e+03
 -2.021e+03 -4.419e+03  7.535e+02 -2.171e+03 -8.416e+00]
weight 23: [ -36.742  837.232  381.107  605.016  466.919 1232.526  596.345 1153.759
  663.743 4223.769  -44.295]
weight 24: [-240.81  1032.091  739.501 1493.419  489.845 1095.727 -620.81  1597.372
  -84.785 1659.163  -27.47 ]
weight 25: [ 8933.688 -7275.224 -3000.222  3933.563 -7933.528  2070.66   6966.425
  4725.953 -1637.751  2722.938   184.697]
weight 26: [  107.244  2600.82   -473.359  2102.009 -3944.789   395.092  3667.583
  2017.047  -813.439  1828.218    61.49 ]
weight 27: [  972.497  2627.503  -701.417  1581.712 -2145.905   324.818  1492.625
  1159.267  -696.755 -2274.749    51.29 ]
weight 28: [-6.814e+03  1.000e+04  1.264e+03 -2.300e-01 -1.233e+03 -2.597e+03
  1.991e+03 -1.323e+03  5.710e+01  2.860e+03 -2.564e+01]"""

In [26]:
import re
import ast

def preprocess_text(text):
    out = text.replace("\n", " ")
    out = re.sub(r'\s+', ' ', out)
    out = re.sub(r'\s+', ' ', out)

    return ["[{}]".format(l.split(":")[-1].strip("[] ").replace(" ", ",")) for l in out.split("weight")][1:]

out = preprocess_text(w_array_text)

w_array = [np.array(ast.literal_eval(o)) for o in out]
# out

In [46]:
w_init = """weight : [[ 146.888  257.333  120.706 -273.091  597.232   77.819 -430.544   66.271
  214.027 -211.351  136.076]]"""

init_w = np.array(ast.literal_eval(preprocess_text(w_init)[0]))
init_w

array([ 146.888,  257.333,  120.706, -273.091,  597.232,   77.819,
       -430.544,   66.271,  214.027, -211.351,  136.076])

In [47]:
critic_init_fading_factor = 0.8

total_sum = 0
weight_list = []
N = len(w_array)  
for i, w_i in enumerate(w_array, start=0):
    weight_list.append(critic_init_fading_factor ** i)
    total_sum += weight_list[-1] * w_i
    # print(f"weight {i}:", w_i)

weighted_average = total_sum / np.sum(weight_list)
Delta_w =  weighted_average - init_w

Delta_w, weighted_average

(array([ 269.934433  , -295.95213095,   58.44535839,  454.52816519,
          78.24568241,  371.2287857 , -351.8874298 ,   74.98203886,
        -131.15926816,  235.26933329,  -34.50815998]),
 array([ 416.822433  ,  -38.61913095,  179.15135839,  181.43716519,
         675.47768241,  449.0477857 , -782.4314298 ,  141.25303886,
          82.86773184,   23.91833329,  101.56784002]))

In [37]:
from utilities import (
    uptria2vec,
    to_row_vec,
    to_scalar,
    push_vec,
    rep_mat
    )

def critic_model_quad_mix(observation, action, critic_weight_tensor):
    feature_tensor = np.hstack(
                [
                    to_row_vec(observation) ** 2,
                    np.kron(to_row_vec(observation), to_row_vec(action)),
                    to_row_vec(action) ** 2,
                ]
            )
    
    result = critic_weight_tensor @ feature_tensor.T

    return to_scalar(result) 

In [38]:
calf_penalty_coeff = 0.5
next_init_w = init_w + calf_penalty_coeff * Delta_w
next_init_w

array([ 109.32136479,  125.34241632,   75.77318406, -120.92856855,
        356.75672684,   77.56061361, -282.61860998,   45.29364313,
        114.14621554, -103.61676539,   76.78029926])

In [44]:
critic_model_quad_mix(np.array([[1, 1, np.pi]]),
                      np.array([0.22, -2.84]),
                      next_init_w) 

389.564188557687

In [45]:
w_init = """weight : [[-386.85  -117.643 -599.681 -607.826 -421.861 -223.884  352.707  253.709
   243.525  228.139  645.155]]"""

init_w = np.array(ast.literal_eval(preprocess_text(w_init)[0]))
init_w

array([-386.85 , -117.643, -599.681, -607.826, -421.861, -223.884,
        352.707,  253.709,  243.525,  228.139,  645.155])

In [43]:
critic_model_quad_mix(np.array([[1, 1, np.pi]]),
                      np.array([0.22, -2.84]),
                      init_w)

-3192.490945270644